title: Jhennifer Smith
description: Olá! Me chamo Jhennifer e sou uma desenvolvedora de software em desenvolvimento, fiz esse site para compartilhar o que estou aprendendo nesta minha caminhada! 
site_title: 'Jhennifer Smith'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: jhennifersmith
blog_url: https://jhennifersmith.github.io
email: jhennifersmithsoares@gmail.com
keybase_username: jhennifersmith
twitter_username: jhennismith
instagram_username: jhennifersmith

# absolute or relative
profile_picture: assets/images/foto.jfif

# Google Analytics ID
google_analytics: 
