title: Jhennifer Smith
description: Desenvolvedora back-end
site_title: 'Jhennifer Smith'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: jhennifersmith
blog_url: https://jhennifersmith.github.io
email: jhennifersmithsoares@gmail.com
keybase_username: jhennifersmith
twitter_username: jhennismith

# absolute or relative
profile_picture: assets/images/foto.jfif

# Google Analytics ID
google_analytics: 
