title: Jhennifer Smith
description: Desenvolvedora de software em desenvolvimento
site_title: 'Jhennifer Smith'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: jhennifersmith
blog_url: https://jhennifersmith.github.io
email: jhennifersmithsoares@gmail.com
keybase_username: jhennifersmith
twitter_username: jhennismith
instagram_username: jhennifersmith
linkedin_username: jhennifer-smith-029003196

# absolute or relative
profile_picture: assets/images/foto.jfif

# Google Analytics ID
google_analytics: 
